spring.application.name=Teamjavaprogramming

spring.datasource.url=jdbc:mysql://localhost:3306/teamjavaprogramming
spring.datasource.username=root
spring.datasource.password=czx20030320!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true